name: attendance-system
services:
  - name: backend
    type: web
    build:
      type: buildpack
    instance_type: nano
    ports:
      - port: 3000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    health_check:
      http:
        path: /health
    regions:
      - fra